#!/stage1/busybox sh
export _PATH="$PATH"
export PATH=/stage1

busybox cd /
busybox date >>boot.txt
exec >>boot.txt 2>&1
busybox rm init
busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

while ! busybox test -d /sys/dev/block/179:0 ; do
	busybox echo "waiting for internal mmc" >>boot.txt
	busybox sleep 1
done

/lvm/sbin/lvm vgscan --mknodes --ignorelockingfailure
/lvm/sbin/lvm vgchange -aly --ignorelockingfailure

busybox mount -t ext4 /dev/lvpool/system /system
busybox mount -t yaffs2 /dev/block/mtdblock3 /cache

image=/stage1/ramdisk.cpio

if busybox test -e /cache/.startrecovery || \
   busybox grep -q bootmode=2 /proc/cmdline || \
   busybox grep -q bootmode=9 /proc/cmdline; then

	# recovery boot
	busybox echo 'RECOVERY BOOT' >>boot.txt
	busybox rm -fr /cache/.startrecovery
	image=/stage1/ramdisk-recovery.cpio
	busybox echo "loading ramdisk-recovery.img" >>boot.txt

	# disable lpm
	busybox echo 0 > /sys/class/power_supply/battery/charging_mode_booting

elif ! busybox test -e /system/build.prop ; then

	# emergency boot
	busybox echo "EMERGENCY BOOT" >>boot.txt
	busybox umount /cache
	erase_image cache
	busybox mount -t yaffs2 /dev/block/mtdblock3 /cache

	if ! busybox test -e /cache/recovery ; then
		busybox mkdir /cache/recovery
	fi

	busybox mount -t vfat /dev/block/mmcblk0p1 /sdcard
	busybox sleep 1

	if busybox test -e /sdcard/omni.cfg ; then
		busybox echo "installing: `busybox cat /sdcard/omni.cfg`" >>boot.txt
		busybox echo "creating recovery command" >>boot.txt
		busybox touch /cache/recovery/command
		busybox echo "--update_package=`busybox cat /sdcard/omni.cfg`" > /cache/recovery/command
	else
		busybox echo "omni.cfg not found" >>boot.txt
	fi

	busybox echo "loading ramdisk-recovery.img" >>boot.txt
	image=/stage1/ramdisk-recovery.cpio

	# disable lpm
	busybox echo 0 > /sys/class/power_supply/battery/charging_mode_booting

	# umount sdcard
	busybox umount /sdcard

else
	# android boot
	busybox echo "ANDROID BOOT" >>boot.txt
	busybox echo "loading ramdisk.img" >>boot.txt
fi

busybox umount /cache
busybox umount /system
busybox rmdir /sdcard

busybox cpio -ui < $image

if busybox grep -q mode=charger /proc/cmdline ; then
	busybox cp /sbin/device_healthd /sbin/healthd
	busybox chmod 775 /sbin/healthd
fi

busybox umount /sys
busybox umount /proc
busybox date >>boot.txt
busybox rm -fr /stage1 /dev/*
export PATH="${_PATH}"
exec /init
